deploy_functions:
  - CLOUD_FUNCTION
  - MAIN_APP
gcp_projects:
  - name: 'ualr-cybersecurity'
    credential: 'C:\Users\pdhuff\.gcp\ualr-cybersecurity.json'
  - name: 'trojan-cybergym'
    credential: 'C:\Users\pdhuff\.gcp\trojan-cybergym.json'
  - name: 'cln-cyber-arena'
    credential: 'C:\Users\pdhuff\.gcp\cln-cyber-arena.json'
  - name: 'ncae-ncta'
    credential: 'C:\Users\pdhuff\.gcp\ncae-ncta.json'
#  - name: 'virtual-arkansas'
#    credential: 'C:\Users\pdhuff\.gcp\virtual-arkansas.json'
