version: '1'

workout:
  name: "Practitioner Level Network Security"
  workout_description: "Use this Cyber Arena lab to complete assignments in the Practitioner course for information and network security."
  teacher_instructions_url:
  student_instructions_url:
  build_type: "compute"
  hourly_cost: 0.14
  author: TBD

student_entry:
  type: rdp
  username: cyberarena
  password: "P@55w0rd!"
  security-mode: "Any"
  network: external-network
  ip: 10.1.1.44

networks:
  - name: external-network
    subnets:
      - name: default
        ip_subnet: 10.1.1.0/24

servers:
  - name: kali
    image: image-cyberarena-kali-desktop
    machine_type: "n1-standard-1"
    nics:
      - network: external-network
        internal_IP: 10.1.1.44
        subnet: default
        external_NAT: true
  - name: metasploitable
    image: image-nsa-metasploitable
    machine_type: "n1-standard-2"
    nics:
      - network: external-network
        internal_IP: 10.1.1.45
        subnet: default
        external_NAT: true

# List network routes. Multiple routes may be listed using YAML block sequence format
routes:

# List all firewall rules. Multiple rules may be listed using YAML block sequence format.
firewall_rules:
  - name: allow-all-local-external
    network: external-network
    target_tags: []
    protocol: tcp
    ports: ["tcp/any", "udp/any", "icmp/any"]
    source_ranges: ["10.1.1.0/24"]

assessment:
